// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0kwfQlzHu8Kmbpkdasb9WXt7i4wwJE6g',
    appId: '1:218609860682:web:62b5e02431d1b4ff12e6b3',
    messagingSenderId: '218609860682',
    projectId: 'edu-track-1',
    authDomain: 'edu-track-1.firebaseapp.com',
    storageBucket: 'edu-track-1.firebasestorage.app',
    measurementId: 'G-VP6VJ6LSB0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-YAMdB1kSQAZDCML9GeIcv3ovN7TSu8',
    appId: '1:218609860682:android:e1c8cd65b5cd243a12e6b3',
    messagingSenderId: '218609860682',
    projectId: 'edu-track-1',
    storageBucket: 'edu-track-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRtwBt6GDAAv-6Dm5X5CSYi8fkYua5fhs',
    appId: '1:218609860682:ios:8dd1155f06fad54112e6b3',
    messagingSenderId: '218609860682',
    projectId: 'edu-track-1',
    storageBucket: 'edu-track-1.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRtwBt6GDAAv-6Dm5X5CSYi8fkYua5fhs',
    appId: '1:218609860682:ios:8dd1155f06fad54112e6b3',
    messagingSenderId: '218609860682',
    projectId: 'edu-track-1',
    storageBucket: 'edu-track-1.firebasestorage.app',
    iosBundleId: 'com.example.edutrack',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0kwfQlzHu8Kmbpkdasb9WXt7i4wwJE6g',
    appId: '1:218609860682:web:7d7e2d9cf44b90e612e6b3',
    messagingSenderId: '218609860682',
    projectId: 'edu-track-1',
    authDomain: 'edu-track-1.firebaseapp.com',
    storageBucket: 'edu-track-1.firebasestorage.app',
    measurementId: 'G-56V06R606J',
  );

}